/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-sep.-2021 09:54:30 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */
/* Drop Tables */

DROP TABLE IF EXISTS products CASCADE
;

DROP TABLE IF EXISTS shopping_cart_products CASCADE
;

DROP TABLE IF EXISTS shopping_carts CASCADE
;

DROP TABLE IF EXISTS users CASCADE
;

/* Create Tables */

CREATE TABLE products
(
	id serial NOT NULL,
	name varchar(50) NULL,
	description varchar(50) NULL,
	price numeric NULL,
	currency varchar(50) NULL,
	status varchar(50) NULL
)
;

CREATE TABLE shopping_cart_products
(
	id serial NOT NULL,
	shopping_cart_id serial NOT NULL,
	product_id bigint NULL,
	quantity integer NULL
)
;

CREATE TABLE shopping_carts
(
	id serial NOT NULL,
	user_id serial NOT NULL,
	last_modified_timestamp timestamp without time zone NULL,
	creation_time_stamp timestamp without time zone NULL,
	status varchar(50) NOT NULL
)
;

CREATE TABLE users
(
	id serial NOT NULL,
	name varchar(50) NULL,
	last_name varchar(50) NULL,
	vip boolean NULL,
	identification bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE products ADD CONSTRAINT PK_products
	PRIMARY KEY (id)
;

ALTER TABLE shopping_cart_products ADD CONSTRAINT PK_shopping_cart_products
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_shopping_cart_products_products ON shopping_cart_products (product_id ASC)
;

CREATE INDEX IXFK_shopping_cart_products_shopping_carts ON shopping_cart_products (shopping_cart_id ASC)
;

ALTER TABLE shopping_carts ADD CONSTRAINT PK_shopping_carts
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_shopping_carts_users ON shopping_carts (user_id ASC)
;

ALTER TABLE users ADD CONSTRAINT PK_users
	PRIMARY KEY (id)
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

 

/***** INITIAL CREATION FOR PRODUCTS AND USERS *****/
insert into products values (DEFAULT, 'MotoG 6', 'MotoG 6', 29999.00, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'MotoG 7', 'MotoG 7', 30000.33, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Remera 1', 'Remera 1', 1100, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Remera 2', 'Remera 2', 1200, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Remera 3', 'Remera 3', 1300.3, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Remera 4', 'Remera 4', 1400.4, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Remera 5', 'Remera 5', 1500.5, 'ARG', 'ACTIVE');

insert into products values (DEFAULT, 'Buzo 1', 'Buzo 1', 3200, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Buzo 2', 'Buzo 2', 3500, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Buzo 3', 'Buzo 3', 3300.55, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Buzo 4', 'Buzo 4', 3400.23, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Buzo 5', 'Buzo 5', 3500.56, 'ARG', 'ACTIVE');

insert into products values (DEFAULT, 'Manzana', 'Manzana', 15, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Banana', 'Banana', 20, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Pera', 'Pera', 15, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Sandia', 'Sandia', 30, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Naranja', 'Naranja', 5, 'ARG', 'ACTIVE');
insert into products values (DEFAULT, 'Kiwi', 'Kiwi', 14, 'ARG', 'ACTIVE');


insert into users values (DEFAULT, 'Lucas 1', 'Moreno 1', false, 31900901);
insert into users values (DEFAULT, 'Lucas 2', 'Moreno 2', false, 31900902);
insert into users values (DEFAULT, 'Lucas 3', 'Moreno 3', false, 31900903);
insert into users values (DEFAULT, 'Lucas 4', 'Moreno 4', false, 31900904);
insert into users values (DEFAULT, 'Lucas 5', 'Moreno 5', false, 31900905);
insert into users values (DEFAULT, 'Lucas 6', 'Moreno 6', false, 31900906);
insert into users values (DEFAULT, 'Lucas 7', 'Moreno 7', false, 31900907);
insert into users values (DEFAULT, 'Lucas 8', 'Moreno 8', false, 31900908);
insert into users values (DEFAULT, 'Lucas 9', 'Moreno 9', false, 31900909);
insert into users values (DEFAULT, 'Lucas 10', 'Moreno 10', false, 31900910);


insert into users values (DEFAULT, 'Lucas 11', 'Moreno 11', true, 31900911);
insert into users values (DEFAULT, 'Lucas 12', 'Moreno 12', true, 31900912);
insert into users values (DEFAULT, 'Lucas 13', 'Moreno 13', true, 31900913);
insert into users values (DEFAULT, 'Lucas 14', 'Moreno 14', true, 31900914);
insert into users values (DEFAULT, 'Lucas 15', 'Moreno 15', true, 31900915);
insert into users values (DEFAULT, 'Lucas 16', 'Moreno 16', true, 31900916);
insert into users values (DEFAULT, 'Lucas 17', 'Moreno 17', true, 31900917);
insert into users values (DEFAULT, 'Lucas 18', 'Moreno 18', true, 31900918);
insert into users values (DEFAULT, 'Lucas 19', 'Moreno 19', true, 31900919);
insert into users values (DEFAULT, 'Lucas 20', 'Moreno 20', true, 31900911);
